In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.exceptions import ConvergenceWarning
warnings.filterwarnings("ignore", category=ConvergenceWarning)


In [15]:
df = pd.read_csv("C:/Users/krith/OneDrive/Desktop/projects/Regression/archive/kc_house_data.csv")

In [16]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [17]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [19]:
df.describe().T

count          mean           std           min  \
id             21613.0  4.580302e+09  2.876566e+09  1.000102e+06   
price          21613.0  5.400881e+05  3.671272e+05  7.500000e+04   
bedrooms       21613.0  3.370842e+00  9.300618e-01  0.000000e+00   
bathrooms      21613.0  2.114757e+00  7.701632e-01  0.000000e+00   
sqft_living    21613.0  2.079900e+03  9.184409e+02  2.900000e+02   
sqft_lot       21613.0  1.510697e+04  4.142051e+04  5.200000e+02   
floors         21613.0  1.494309e+00  5.399889e-01  1.000000e+00   
waterfront     21613.0  7.541757e-03  8.651720e-02  0.000000e+00   
view           21613.0  2.343034e-01  7.663176e-01  0.000000e+00   
condition      21613.0  3.409430e+00  6.507430e-01  1.000000e+00   
grade          21613.0  7.656873e+00  1.175459e+00  1.000000e+00   
sqft_above     21613.0  1.788391e+03  8.280910e+02  2.900000e+02   
sqft_basement  21613.0  2.915090e+02  4.425750e+02  0.000000e+00   
yr_built       21613.0  1.971005e+03  2.937341e+01  1.900000e+03   
yr_renovated   21613.0  8.440226e+01  4.016792e+02  0.000000e+00   
zipcode        21613.0  9.807794e+04  5.350503e+01  9.800100e+04   
lat            21613.0  4.756005e+01  1.385637e-01  4.715590e+01   
long           21613.0 -1.222139e+02  1.408283e-01 -1.225190e+02   
sqft_living15  21613.0  1.986552e+03  6.853913e+02  3.990000e+02   
sqft_lot15     21613.0  1.276846e+04  2.730418e+04  6.510000e+02   

                        25%           50%           75%           max  
id             2.123049e+09  3.904930e+09  7.308900e+09  9.900000e+09  
price          3.219500e+05  4.500000e+05  6.450000e+05  7.700000e+06  
bedrooms       3.000000e+00  3.000000e+00  4.000000e+00  3.300000e+01  
bathrooms      1.750000e+00  2.250000e+00  2.500000e+00  8.000000e+00  
sqft_living    1.427000e+03  1.910000e+03  2.550000e+03  1.354000e+04  
sqft_lot       5.040000e+03  7.618000e+03  1.068800e+04  1.651359e+06  
floors         1.000000e+00  1.500000e+00  2.000000e+00  3.500000e+00  
waterfront     0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00  
view           0.000000e+00  0.000000e+00  0.000000e+00  4.000000e+00  
condition      3.000000e+00  3.000000e+00  4.000000e+00  5.000000e+00  
grade          7.000000e+00  7.000000e+00  8.000000e+00  1.300000e+01  
sqft_above     1.190000e+03  1.560000e+03  2.210000e+03  9.410000e+03  
sqft_basement  0.000000e+00  0.000000e+00  5.600000e+02  4.820000e+03  
yr_built       1.951000e+03  1.975000e+03  1.997000e+03  2.015000e+03  
yr_renovated   0.000000e+00  0.000000e+00  0.000000e+00  2.015000e+03  
zipcode        9.803300e+04  9.806500e+04  9.811800e+04  9.819900e+04  
lat            4.747100e+01  4.757180e+01  4.767800e+01  4.777760e+01  
long          -1.223280e+02 -1.222300e+02 -1.221250e+02 -1.213150e+02  
sqft_living15  1.490000e+03  1.840000e+03  2.360000e+03  6.210000e+03  
sqft_lot15     5.100000e+03  7.620000e+03  1.008300e+04  8.712000e+05

In [20]:
df.shape

(21613, 21)

In [21]:
df.duplicated().sum()

0

In [22]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [23]:
df.waterfront.unique()

array([0, 1], dtype=int64)

In [24]:
df.view.unique()

array([0, 3, 4, 2, 1], dtype=int64)

In [27]:
df.grade.unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1], dtype=int64)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(4,5, figsize=(10, 8))
axes = axes.flatten()
columns = df.drop(columns=['date', 'id'])

for i, column in enumerate(columns):
    ax = axes[i]
    sns.boxplot(data=df, y=column, ax=ax)

plt.tight_layout()
plt.show()


In [ ]:
df.bedrooms.unique()

In [ ]:
df[df.bedrooms==33]

In [ ]:
df[df['bedrooms']==33]['sqft_living']/df[df['bedrooms']==33]['bedrooms']

In [ ]:
df.sqft_living.mean()/df.bedrooms.mean()

The average sqft per bedroom is around 618 sqft but the house with 33 bedrooms has 49 which confirm it is an outlier by entry

In [ ]:
df.drop(15870,inplace=True)

In [ ]:
df.yr_renovated.unique()

beacause of the 0 the other values seems like an outlier where they really arent

In [ ]:
df['date']=pd.to_datetime(df['date'])

In [ ]:
df['date'].head()

In [ ]:
df.head()

In [ ]:
fig , axes = plt.subplots(5,4,figsize=(10,8))
axes = axes.flatten()
cols = df.drop(columns=['id','date'])
for i,column in enumerate(cols):
    sns.histplot(data=df,x=column,ax=axes[i])
    plt.tight_layout()
    

In [ ]:
plt.figure(figsize=(15,8))
sns.heatmap(df.drop(columns=['id','date']).corr(),annot=True,mask=np.triu(df.drop(columns=['id','date']).corr(),+1));

In [ ]:
df.drop(columns=['zipcode','long','yr_built','condition','sqft_lot15'],inplace=True)

In [ ]:
plt.figure(figsize=(15,8))
sns.heatmap(df.drop(columns=['id','date']).corr(),annot=True,mask=np.triu(df.drop(columns=['id','date']).corr(),+1));

# Model Building 

In [ ]:
x = df.drop(columns=['id','date','price'])
y = df.pop('price')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
print('x train :',len(x_train),'y train :',len(y_train))
print('x test :',len(x_test),'y test :',len(y_test))

In [ ]:
df.columns

# model building using pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

In [ ]:
pipeline_lr = Pipeline([('Scale1',StandardScaler()),('lr',LinearRegression())])

In [ ]:
pipeline_ls = Pipeline([('scale2',StandardScaler()),('ls',Lasso(alpha=0.5,max_iter=5000))])

In [ ]:
pipeline_dt = Pipeline([('scale3',StandardScaler()),('dt',DecisionTreeRegressor())])

In [ ]:
pipeline_rfr = Pipeline([('scale4',StandardScaler()),('rfr',RandomForestRegressor())])

In [ ]:
pipeline_knn = Pipeline([('scale5',StandardScaler()),('knn',KNeighborsRegressor())])

In [ ]:
pipeline_xgb = Pipeline([('scale6',StandardScaler()),('xgb',XGBRegressor())])

In [ ]:
pipelines = [pipeline_lr,pipeline_ls,pipeline_dt,pipeline_rfr,pipeline_knn,pipeline_xgb]

In [ ]:
for i in pipelines:
    i.fit(x_train,y_train)

In [ ]:
from sklearn.model_selection import cross_val_score
cv_result_rmse=[]

In [ ]:
for i, model in enumerate(pipelines):
    cv_scores = cross_val_score(model, x_train, y_train, scoring='neg_root_mean_squared_error', cv=12)
    avg_score = -cv_scores.mean()
    print(f"Model {i+1}: {avg_score}")

In [ ]:
pred = pipeline_xgb.predict(x_test)

In [ ]:
print('R squared :',r2_score(y_test,pred))

In [ ]:
print("Adjusted R^2:",1 - (1-r2_score(y_test, pred))*(len(y_test)-1)/(len(y_test)-x_test.shape[1]-1))

In [ ]:
print('mean absolute error :',mean_absolute_error(y_test,pred))

# ANN

Scaling 

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
ss = StandardScaler()

In [ ]:
xs_train=ss.fit_transform(x_train)
xs_test=ss.transform(x_test)

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(128,input_dim=13,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='linear'))

In [ ]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics='mae')

In [ ]:
model.summary()

In [ ]:
history = model.fit(xs_train,y_train,epochs=100,validation_split=0.2,)

In [ ]:
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(loss) + 1)
plt.plot(epochs, loss, 'y', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
acc = history.history['mae']
val_acc = history.history['val_mae']
plt.plot(epochs, acc, 'y', label='Training MAE')
plt.plot(epochs, val_acc, 'r', label='Validation MAE')
plt.title('Training and validation MAE')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

In [ ]:
pred_ann = model.predict(xs_test)

In [ ]:
print('R squared :',r2_score(y_test,pred_ann))

# XGB performs better

In [ ]:
import pickle

In [ ]:
pipeline_xgb

In [ ]:
xgb = pipeline_xgb.named_steps['xgb']

In [ ]:
xgb

In [ ]:
model = xgb 

In [ ]:
filename='modelpickleR'

In [ ]:
with open(filename,'wb') as file:
    pickle.dump(model,file)

In [ ]:
df.columns

In [29]:
import flask
import sklearn

print(f"Flask version: {flask.__version__}")
print(f"scikit-learn version: {sklearn.__version__}")


Flask version: 2.2.2
scikit-learn version: 1.2.1
